// Listado de rubros para el <select>
export const rubros = [
   "Arreglos",
   "Auto",
   "Bebe",
   "Comida",
   "Educacion",
   "Entretenimiento",
   "Estetica",
   "Expensas",
   "Farmacia",
   "Gimnasio",
   "Hogar",
   "Impuestos",
   "Indumentaria",
   "Limpieza",
   "Mascota",
   "Regalos",
   "Salidas",
   "Salud",
   "Shopping",
   "Suscripciones",
   "Supermercado",
   "Tecnología",
   "Transporte",
   "Variado",
   "Viaje"
].sort()